apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: final
spec:
  storageClassName: sc-final
  volumeName: my-pv
  resources:
    requests:
      storage: 4Gi
  accessModes:
  - ReadWriteOnce
  
  